default = {
    'ascending_tiles_x': True,
    'ascending_tiles_y': True,
    'channel': None,
    'equal_shape': False,
    'input_folder': '/media/dimitris/My Passport/data/Christina/test_coppafish-tools/if_reg_output/if/channel_0',
    'invert_x':  False,
    'invert_y': False,
    'max_dx': 192,
    'max_dy': 192,
    'max_dz': 20,
    'n_of_workers':  None,
    'output_file':  'stitch.yml',
    'overlap': 60.0,
    'overlap_h':  231,
    'overlap_v':  231,
    'px_size_xy':  0.26,
    'px_size_z': 0.5,
    'recursive': False,
    'z_samples': 1,
    'z_stride': None,
}
